### ISSUE TITLE
How to use GeDI on BART？

### ISSUE THREAD

**Issue by 20174376** [talaugust/definition-complexity#1]
Hello, I noticed that you used GEDI on BART, but does GEDI only support GPT? I want to ask how you get GEDI to support BART. Thank you!

**Comment by talaugust** [comment]
Hi, thanks for your question, and sorry it took me so long to get back to you! GEDI did not support BART out of the box, I had to train new GEDI models to use for BART. I can look for that code to send.

**Comment by 20174376** [comment]
Thank you very much for your reply. If possible, could you please send me a code? Thank you again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "talaugust/definition-complexity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月27日(星期六) 凌晨2:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [talaugust/definition-complexity] How to use GeDI on BART？ (Issue #1)





 
Hi, thanks for your question, and sorry it took me so long to get back to you! GEDI did not support BART out of the box, I had to train new GEDI models to use for BART. I can look for that code to send.
